version: '3.8'
services:
  backend:
    build:
      context: ./calendar-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/training_calendar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: serban
    depends_on:
      - db
  frontend:
    build: .
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/www:/var/www/certbot
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: serban
      POSTGRES_DB: training_calendar
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
